/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithi;

import static baithi.Tool.DESEDE_ENCRYPTION_SCHEME;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.security.spec.KeySpec;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.swing.JOptionPane;
import sun.misc.BASE64Decoder;

/**
 *
 * @author ASUS
 */
public class giaima extends javax.swing.JFrame {

    /**
     * Creates new form giaima
     */
    
    Tool a= new Tool();
    public giaima() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtD3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtE3 = new javax.swing.JTextArea();
        txtE1 = new javax.swing.JTextField();
        txtM2 = new javax.swing.JTextField();
        txtH2 = new javax.swing.JTextField();
        txtM3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtM1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txth2phay = new javax.swing.JTextArea();
        txtk3 = new javax.swing.JTextField();
        txtk1 = new javax.swing.JTextField();
        mofile = new javax.swing.JButton();
        tachchuoi = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        h2phay = new javax.swing.JButton();
        sosanh = new javax.swing.JButton();
        D3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("e3");

        jLabel2.setText("d3");

        jLabel3.setText("e1");

        jLabel4.setText("m2");

        jLabel5.setText("h2");

        jLabel6.setText("m3");

        jLabel7.setText("m1");

        jLabel8.setText("h2'");

        jLabel9.setText("k3");

        jLabel10.setText("k1");

        txtD3.setColumns(20);
        txtD3.setRows(5);
        jScrollPane1.setViewportView(txtD3);

        txtE3.setColumns(20);
        txtE3.setRows(5);
        jScrollPane2.setViewportView(txtE3);

        txtE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1ActionPerformed(evt);
            }
        });

        txtM1.setColumns(20);
        txtM1.setRows(5);
        jScrollPane3.setViewportView(txtM1);

        txth2phay.setColumns(20);
        txth2phay.setRows(5);
        jScrollPane4.setViewportView(txth2phay);

        txtk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtk3ActionPerformed(evt);
            }
        });

        mofile.setText("mo file e3");
        mofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mofileActionPerformed(evt);
            }
        });

        tachchuoi.setText("tach chuoi D3");
        tachchuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tachchuoiActionPerformed(evt);
            }
        });

        m1.setText("M1=De[E1] vs K1");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        h2phay.setText("H2'");
        h2phay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2phayActionPerformed(evt);
            }
        });

        sosanh.setText("ss");
        sosanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosanhActionPerformed(evt);
            }
        });

        D3.setText("D3=De[E3] vs K3");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtM3)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(txtE1)
                            .addComponent(txtH2)
                            .addComponent(txtM2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtk3)
                            .addComponent(txtk1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mofile)
                                    .addComponent(tachchuoi)
                                    .addComponent(m1)
                                    .addComponent(h2phay)
                                    .addComponent(D3))
                                .addGap(0, 49, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(sosanh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(mofile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtk3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tachchuoi)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(m1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h2phay)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(sosanh)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(165, 165, 165))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        String e1= txtE1.getText();
        String k1 = txtk1.getText();
        String kq= Tool.DeDes(e1, k1);
        txtM1.setText(kq);
    }//GEN-LAST:event_m1ActionPerformed

    private void mofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mofileActionPerformed
        try{
            BufferedReader br = null;
            String fileName= "D:\\e3.txt";
            br = new BufferedReader(new FileReader(fileName));
            
            StringBuffer sb = new StringBuffer();
            
            JOptionPane.showMessageDialog(null, "da mo file thanh cong");
            
            char[] ca= new char[5];
            while (br.ready())
            {
                int len= br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du lieu la :" + " " + sb);
            String chuoi= sb.toString();
            txtE3.setText(chuoi);
            
        }
        catch(IOException ex)
        {
            Logger.getLogger(giaima.class.getName()) .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mofileActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        String e3= txtE3.getText();
        String k3= txtk3.getText();
        String kq=DeDes3(e3, k3);
        txtD3.setText(kq);
    }//GEN-LAST:event_D3ActionPerformed

    private void tachchuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tachchuoiActionPerformed
        String d3 = txtD3.getText();
        String[] part = d3.split("~");
        txtE1.setText(part[0]);
        txtM2.setText(part[1]);
        txtH2.setText(part[2]);
        txtM3.setText(part[3]);
        
    }//GEN-LAST:event_tachchuoiActionPerformed

    private void h2phayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2phayActionPerformed
        String e1= txtE1.getText();
        String m2 = txtM2.getText();
        String bam= e1+m2;
        //String kq= Tool.MD5(bam);
        //String kq= a.SHA(bam);
        txth2phay.setText(a.SHA(bam));
    }//GEN-LAST:event_h2phayActionPerformed

    private void sosanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosanhActionPerformed
        String hexString = txtH2.getText();
        String chuoi = txth2phay.getText();
        Boolean k = hexString.toString().equals(chuoi);
         if(k==true){
         JOptionPane.showMessageDialog(null, "Dung");}
         else{
             JOptionPane.showMessageDialog(null, "sai");
         }
    }//GEN-LAST:event_sosanhActionPerformed

    private void txtk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtk3ActionPerformed

    private void txtE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1ActionPerformed

    private static final String UNICODE_FORMAT = "UTF8";
    public static final String DESEDE_ENCRYPTION_SCHEME= "DESede";
    private KeySpec myKeySpec;
    private SecretKeyFactory mySecretKeyFactory;
    private Cipher cipher;
    byte[] KeyAsBytes;
    private String myEncryptionKey;
    private String myEncryptionScheme;
    SecretKey key;
    
    public String DeDes3(String vb, String txtkhoa){
        try{
            myEncryptionKey= txtkhoa;
            myEncryptionScheme = DESEDE_ENCRYPTION_SCHEME;
            KeyAsBytes = myEncryptionKey.getBytes(UNICODE_FORMAT);
            myKeySpec = new DESedeKeySpec(KeyAsBytes);
            mySecretKeyFactory = SecretKeyFactory.getInstance(myEncryptionScheme);
            cipher= Cipher.getInstance(myEncryptionScheme);
            key= mySecretKeyFactory.generateSecret(myKeySpec);
            System.out.println("khoa ma hoa k: "+key);
            
            String plainText= vb;
            String encrypted = decrypt(plainText);
            System.out.println("Encrypted Value: "+ encrypted);
            return encrypted;
        }
        catch(Exception e){
           
        }
        return null;
    }
    public String decrypt(String encrypted){
        String unencrypted = null;
        try{
            cipher.init(Cipher.DECRYPT_MODE,key);
            BASE64Decoder base64decoder = new BASE64Decoder();
            byte[] encryptedText= base64decoder.decodeBuffer(encrypted);
            byte[] plainText = cipher.doFinal(encryptedText);
            String a = new String(plainText);
            System.out.println("chuoi plaintext: "+a);
            unencrypted = a;
        }catch(Exception e){
            e.printStackTrace();
        }
        return unencrypted;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D3;
    private javax.swing.JButton h2phay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton m1;
    private javax.swing.JButton mofile;
    private javax.swing.JButton sosanh;
    private javax.swing.JButton tachchuoi;
    private javax.swing.JTextArea txtD3;
    private javax.swing.JTextField txtE1;
    private javax.swing.JTextArea txtE3;
    private javax.swing.JTextField txtH2;
    private javax.swing.JTextArea txtM1;
    private javax.swing.JTextField txtM2;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextArea txth2phay;
    private javax.swing.JTextField txtk1;
    private javax.swing.JTextField txtk3;
    // End of variables declaration//GEN-END:variables
}
